### ISSUE TITLE
/System/Library/PrivateFrameworks/AOSKit.framework/AOSKit no longer exists

### ISSUE THREAD

**Issue by JJTech0130** [vtky/AppleIDAuth#1]
Pretty simple. `/System/Library/PrivateFrameworks/AOSKit.framework/AOSKit` no longer exists (on macOS Monterey). Not sure if Apple moved it? If you could provide some insight, that'd be great.

**Comment by biemster** [comment]
I've just peeked in a Monterey 12.3 VM and `AOSKit.framework` is still there, do you maybe remember with which update it got removed?

**Comment by JJTech0130** [comment]
@biemster The *framework* is still there, but is there any binaries in it?

**Comment by JJTech0130** [comment]
Specifically, when I try to run
```
xcrun tapi stubify -o AOSKit.tbd /System/Library/PrivateFrameworks/AOSKit.framework/AOSKit
```
I get the following error:
```
error: no such file or directory: '/System/Library/PrivateFrameworks/AOSKit.framework/AOSKit'
```
It appears that AOSKit.framework itself is still there, but Apple removed the actual contents and only left the localization stuff and some helpers.

**Comment by biemster** [comment]
You are right @JJTech0130 , the binary is not there anymore. Oddly enough, calling `retrieveOTPHeadersForDSID` using the framework path still works:
```python
import objc; from Foundation import NSBundle, NSClassFromString

AOSKitBundle = NSBundle.bundleWithPath_('/System/Library/PrivateFrameworks/AOSKit.framework')
objc.loadBundleFunctions(AOSKitBundle, globals(), [("retrieveOTPHeadersForDSID", '')])
util = NSClassFromString('AOSUtilities')

print(util.retrieveOTPHeadersForDSID_("-2"))
```
maybe the functions are relocated? I'm going to have a search now.

**Comment by novitae** [comment]
> maybe the functions are relocated? I'm going to have a search now.

*A year later.*

Did you find anything ? Is there a way to dump a Framework from the memory ? AOSKit exists on iOS 12 if we can't dump it from macOS.

After reading [@vtky's article](https://vtky.github.io/2020/05/19/appleid-auth-part-1), I manage to download `AOSKit.dll`, and it seems, when disassembling, that the function he took a screenshot of at the end is very different on the `.dll` file I have. So I assume, and his articles suggests it, that he then dumped the macOS `AOSKit` executable, and disassembled it.

@vtky's if you read this and what I said upper is the case, would you still have the executable I'm searching for ? Thanksssss

**Comment by novitae** [comment]
@JJTech0130 The script upper here works to gen authentication data on the case I couldn't solve last time on our discord convo, if you remember. I just managed to dump the executable, I can send it to you if you're interested !

**Comment by JJTech0130** [comment]
It has not actually been removed, just put into the "dyld shared cache", as have all frameworks on modern macOS. See https://theapplewiki.com/wiki/Dev:Dyld_shared_cache

[AOSKit_dyld_cache_arm64e.zip](https://github.com/vtky/AppleIDAuth/files/13467949/AOSKit_dyld_cache_arm64e.zip)
[AOSKit-simruntime.zip](https://github.com/vtky/AppleIDAuth/files/13467952/AOSKit-simruntime.zip)

For your convenience, I have attached both from the version of macOS I am currently running.

**Comment by JJTech0130** [comment]
I'm closing the issue, I was just uninformed about how frameworks work on modern versions of macOS

**Comment by andrewpedia** [comment]
the extracted lib file needs address repairment,right?
